// QA tab — Rules (qa-tab build plan §3; qa-tab.html §QRL zone 11). The stage
// tab rules half: three editable markdown files that the QA Agent and
// Reviewer read when they run the stage. Edits write back to the on-disk
// project folder (testing/qa-rules.md, QA-AGENT.md, REVIEWER-AGENT.md) via the
// rules PUT — the same fixed-filename allowlist + resolveInside + 1 MB cap
// contained server-side (F-SEC-2 conventions). The 1 MB cap is effective: the
// global json gate (index.ts) pre-empts the route; the handler byte-check is
// defense-in-depth (SA5 disposition, DR4 finding, 2026-09-17). Playwright
// config is read-only here (generated by the stack template; not steered from
// this screen).

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link, Navigate, useOutletContext, useParams } from 'react-router-dom';
import {
  QaHttpError,
  QA_RULES_FILENAMES,
  fetchQaRules,
  saveQaRules,
  type QaRulesFile,
} from '../../lib/api';
import type { ProjectOutletContext } from '../ProjectDetailScreen';

type Notice = { kind: 'success' | 'error'; text: string };

const FILE_META: Record<
  QaRulesFile,
  { label: string; hint: string; agent?: boolean; open?: boolean }
> = {
  'qa-rules.md': {
    label: 'QA rules',
    hint: 'Standing rules the QA Agent applies on every run (scopes, tools, evidence).',
  },
  'QA-AGENT.md': {
    label: 'QA Agent · brief',
    agent: true,
    open: true,
    hint: 'Day-to-day instructions for the QA Agent on this project.',
  },
  'REVIEWER-AGENT.md': {
    label: 'Reviewer · brief',
    agent: true,
    hint: 'Instructions for the Reviewer who signs off QA runs.',
  },
};

export function QaRulesScreen() {
  const { id } = useParams();
  const { project } = useOutletContext<ProjectOutletContext>();

  const [files, setFiles] = useState<Record<string, string> | null>(null);
  const [drafts, setDrafts] = useState<Record<QaRulesFile, string>>({
    'qa-rules.md': '',
    'QA-AGENT.md': '',
    'REVIEWER-AGENT.md': '',
  });
  const [dirty, setDirty] = useState<Record<QaRulesFile, boolean>>({
    'qa-rules.md': false,
    'QA-AGENT.md': false,
    'REVIEWER-AGENT.md': false,
  });
  const [saving, setSaving] = useState<QaRulesFile | null>(null);
  const [loadState, setLoadState] = useState<'loading' | 'ok' | 'error'>('loading');
  const [loadError, setLoadError] = useState<string | null>(null);
  const [notice, setNotice] = useState<Notice | null>(null);

  const idOrSlug = id ?? '';

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetchQaRules(idOrSlug);
        if (cancelled) return;
        setFiles(res.files);
        setDrafts((prev) => {
          const next = { ...prev };
          for (const f of QA_RULES_FILENAMES) next[f] = res.files[f] ?? '';
          return next;
        });
        setLoadState('ok');
      } catch (err) {
        if (!cancelled) {
          setLoadError(err instanceof Error ? err.message : 'Could not load the QA rules.');
          setLoadState('error');
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [idOrSlug]);

  const onEdit = useCallback((file: QaRulesFile, content: string) => {
    setDrafts((prev) => ({ ...prev, [file]: content }));
    setDirty((prev) => ({
      ...prev,
      [file]: prev[file] || content !== (files?.[file] ?? ''),
    }));
  }, [files]);

  const save = useCallback(
    async (file: QaRulesFile) => {
      setSaving(file);
      try {
        const res = await saveQaRules(idOrSlug, file, drafts[file]);
        setNotice({ kind: 'success', text: `Saved ${file} (${res.size} B) — written to the project's testing/ folder.` });
        setDirty((prev) => ({ ...prev, [file]: false }));
      } catch (err) {
        if (err instanceof QaHttpError) {
          setNotice({ kind: 'error', text: err.message });
        } else {
          setNotice({ kind: 'error', text: err instanceof Error ? err.message : `Could not save ${file}.` });
        }
      } finally {
        setSaving(null);
      }
    },
    [drafts],
  );

  const totalBytes = useMemo(
    () => QA_RULES_FILENAMES.reduce((n, f) => n + (drafts[f]?.length ?? 0), 0),
    [drafts],
  );

  // Gate on project context (QA is gated). All hooks above so rules hold.
  if (project && !project.context_confirmed) {
    return <Navigate to={`/projects/${idOrSlug}/overview`} replace />;
  }

  return (
    <div className="qa-screen">
      {notice && (
        <div
          className="toast"
          role={notice.kind === 'error' ? 'alert' : 'status'}
          aria-live="polite"
          style={notice.kind === 'error' ? { background: 'var(--blush)' } : undefined}
        >
          <span className="toast-dot" aria-hidden="true" />
          {notice.text}
        </div>
      )}

      {loadState === 'loading' && (
        <div className="center-stage" style={{ minHeight: 320 }}>
          <div className="center-card" style={{ textAlign: 'center' }}>
            <h1>Loading…</h1>
          </div>
        </div>
      )}

      {loadState === 'error' && (
        <div className="center-stage" style={{ minHeight: 320 }}>
          <div className="center-card" style={{ textAlign: 'center' }}>
            <h1>Could not load the QA rules</h1>
            <p className="sub" style={{ textAlign: 'center' }}>{loadError}</p>
            <Link to={`/projects/${idOrSlug}/qa`} className="btn btn-soft btn-pill">
              ← Back to QA list
            </Link>
          </div>
        </div>
      )}

      {loadState === 'ok' && files && (
        <>
          <div className="topbar">
            <Link
              to={`/projects/${idOrSlug}/qa`}
              className="back-arrow"
              aria-label="Back to QA list"
            >
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2}>
                <path d="M15 18l-6-6 6-6" />
              </svg>
              <span>Back to QA list</span>
            </Link>
            <div className="proj-head">
              <h1>QA rules</h1>
              <p className="sub">
                Edits write straight to the project's <b>testing/</b> folder — the QA Agent and
                this project's Reviewer read these files at run time.
              </p>
            </div>
          </div>

          <div className="rules-section">
            {/* Read-only config — Playwright is scaffold-owned, not steered here. */}
            <div className="arch-card">
              <div className="h">
                <h3>Testing framework</h3>
                <span className="pill lock">read-only</span>
              </div>
              <div className="body">
                <ul>
                  <li><b>Playwright</b> · chromium project · UI walk + API probes per run.</li>
                  <li>Screenshots live under the project's <b>qa-evidence/</b> folder and are served
                    by test id + step — never by arbitrary path.</li>
                  <li>Test names reference the PRD acceptance criteria; each test row shows its <b>AC</b> ids.</li>
                  <li><b>Visual diff is deferred</b> by the build plan (qa-tab §2) — the detail
                    screen keeps its gated card with the deferral note.</li>
                </ul>
              </div>
            </div>

            {QA_RULES_FILENAMES.map((file) => {
              const meta = FILE_META[file];
              const dirtyHere = dirty[file];
              const savingHere = saving === file;
              return (
                <div
                  className={meta.agent ? `agent-md-card${meta.open ? ' open' : ''}` : 'md-card'}
                  key={file}
                >
                  <div className="h">
                    <div className="name">
                      <h3>{meta.label}</h3>
                      <span className="path mono">testing/{file}</span>
                    </div>
                    <span
                      className="meta"
                      style={{ color: 'var(--ink-2)', fontSize: 11.5 }}
                    >
                      {new Blob([drafts[file]]).size.toLocaleString()} B
                    </span>
                    {dirtyHere && <span className="pill warn">unsaved</span>}
                    <button
                      type="button"
                      className="btn btn-primary btn-pill"
                      disabled={savingHere || !dirtyHere}
                      onClick={() => void save(file)}
                    >
                      {savingHere ? 'Saving…' : 'Save'}
                    </button>
                  </div>
                  <p className="hint">{meta.hint}</p>
                  {file === 'qa-rules.md' && (
                    <p className="hint" style={{ fontFamily: 'var(--font-mono)', fontSize: 11 }}>
                      # QA rules · this project — one line per rule, applied on every run.
                    </p>
                  )}
                  <textarea
                    value={drafts[file]}
                    onChange={(e) => onEdit(file, e.target.value)}
                    aria-label={`Edit ${meta.label}`}
                    spellCheck={false}
                    rows={16}
                    className="md-edit"
                  />
                </div>
              );
            })}
          </div>

          <p className="sub" style={{ marginTop: 10, fontSize: 11.5, color: 'var(--ink-2)' }}>
            Rules are capped at 1 MB per file and only these three fixed filenames may be written
            through this screen. Save buttons enable when a file is dirty · {totalBytes.toLocaleString()} B
            across the three files in this editor.
          </p>
        </>
      )}
    </div>
  );
}
